---
# Author: Brian Gaber

Parameters:
  Environment:
    Description: "The environment this hosted zone belongs to"
    Type: "String"
    Default: "prod"
    AllowedValues:
      - sandbox
      - development
      - test
      - prod
  DomainName:
    Description: The domain name
    Type: String
    Default: cldsandbox.com
  DeployHostedZone:
      Description: Define whether deploy the hosted zone or not
      Type: String
      Default: no
      AllowedValues:
        - yes
        - no

Conditions:
  CreateHostedZone: !Equals [ !Ref DeployHostedZone, "yes"]

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Condition: CreateHostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone supporting the domain ${DomainName} for the ${Environment} environment.'
      HostedZoneTags:
        Key: Environment
        Value: !Ref Environment

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '*.${DomainName}'
      SubjectAlternativeNames:
        - !Sub '${DomainName}'
      Tags: 
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Ref DomainName
      ValidationMethod: DNS