---
# Author: Brian Gaber
# CareGuard 3 Cognito Cloudformation Template
# Stack can be created from the console or from the AWS CLI.
# If stack is created from the console then resources will be created in the region shown in the upper right.
# If stack is created from the AWS CLI then the region flag must be used or the stack will be created in the AWS default region (us-east-1).
# Example of creating stack from the AWS CLI:
# aws --region us-east-1 cloudformation create-stack --stack-name cg3-cognito-stack --template-body file://cg3-cognito-prod.json --parameters ParameterKey=ActualParamName,ParameterValue=ActualParamValue
# This CloudFormation Template will create the following resources:
# - Route 53 Record

Parameters:
  CreationDate:
    Description: Creation Date
    Type: String
    Default: "2023-03-27 10:30:00"
    AllowedPattern: "^\\d{4}(-\\d{2}){2} (\\d{2}:){2}\\d{2}$"
    ConstraintDescription: Date and time of creation
  CreatedBy:
    Description: Who or what created this Cloudformation stack
    Default: Brian Gaber using CloudFormation
    Type: String
  Application:
    Description: Application Name
    Default: CareGuard 3
    Type: String
  Owner:
    Description: Application Owner
    Default: Rama Pulivarthy
    Type: String
  R53HostedZoneId:
    Description: The Route 53 Hosted Zone Id For careguard.net
    Type: AWS::Route53::HostedZone::Id
    Default: Z18BORQC57TNAS
  CustomDomainName:
    Description: The Prod custom domain name
    Type: String
    Default: auth.careguard.net
  cg3UserPoolDomainCloudFrontDistribution:
    Description: The Prod User Pool Domain CloudFront Distribution
    Type: String
    Default: d2kz6be7s1jjjl.cloudfront.net

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network"
        Parameters:
          - R53HostedZoneId
      - Label:
          default: "Tags"
        Parameters:
          - CreationDate
          - CreatedBy
          - Application
          - Owner
    ParameterLabels:
      CustomDomainName:
        default: "What is the name of the Prod Custom Domain (cannot already be used by an existing User Pool)?"
      R53HostedZoneId:
        default: "What is the Id of the Route 53 Hosted Zone?"

Resources:
  # Create Route 53 DNS Record for Cognito User Pool Domain CloudFront Distribution
  CognitoDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Ref cg3UserPoolDomainCloudFrontDistribution
        HostedZoneId: Z2FDTNDATAQYW2 # from AWS docs
      HostedZoneId: !Ref R53HostedZoneId
      Name: !Ref CustomDomainName
      Type: A
      
Outputs:
  DNSname:
    Description: Route 53 DNS Name
    Value: !Ref CognitoDNSRecord
