---
# Brian Gaber
# IAM User Creation Cloudformation Template
# Stack can be created from the console or from the AWS CLI.
# If stack is created from the console then resources will be created in the region shown in the upper right.
# If stack is created from the AWS CLI then the region flag must be used or the stack will be created in the AWS default region (us-east-1).
# Example of creating stack from the AWS CLI:
# aws --region us-east-1 cloudformation create-stack --stack-name myteststack --template-body file://careguard-user.yaml --parameters ...
# This CloudFormation Template will create one user

Parameters:
  CreationDate:
    Description: Creation Date
    Type: String
    Default: "2023-02-03 10:30:00"
    AllowedPattern: "^\\d{4}(-\\d{2}){2} (\\d{2}:){2}\\d{2}$"
    ConstraintDescription: Date and time of creation
  CreatedBy:
    Description: Tool used to create resources
    Default: CloudFormation
    Type: String
  Application:
    Description: Application Name
    Default: CareGuard 3
    Type: String
  Username:
    Description: User Name
    Default: careguard_for_bitbucket
    Type: String
  Account:
    Description: AWS Account
    Default: 655690556973
    Type: String
  CloudFrontDistID:
    Description: CloudFront Distribution ID
    Default: E1DFZCGNU1GLB8
    Type: String

Resources:
  IAMpolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: ECR Read Only Policy
      ManagedPolicyName: ECR_ReadOnly_Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'ecr:GetRegistryPolicy'
              - 'ecr:DescribeImageScanFindings'
              - 'ecr:GetLifecyclePolicyPreview'
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:DescribeRegistry'
              - 'ecr:DescribePullThroughCacheRules'
              - 'ecr:DescribeImageReplicationStatus'
              - 'ecr:GetAuthorizationToken'
              - 'ecr:ListTagsForResource'
              - 'ecr:ListImages'
              - 'ecr:BatchGetRepositoryScanningConfiguration'
              - 'ecr:GetRegistryScanningConfiguration'
              - 'ecr:BatchGetImage'
              - 'ecr:DescribeImages'
              - 'ecr:DescribeRepositories'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:GetRepositoryPolicy'
              - 'ecr:GetLifecyclePolicy'
            Resource: '*'

  IAMuser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns: 
        - !Ref IAMpolicy
      Policies:
        - PolicyName: CG3_ECR_Write_Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: EcrAccess
                Effect: Allow
                Action:
                  - 'ecr:PutImageTagMutability'
                  - 'ecr:StartImageScan'
                  - 'ecr:PutImageScanningConfiguration'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:BatchDeleteImage'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:ReplicateImage'
                  - 'ecr:PutImage'
                Resource: !Join ["", ["arn:aws:ecr:us-east-1:", !Ref Account, ":repository/cg3-backend"] ]
                #Resource: 'arn:aws:ecr:us-east-1:300899438431:repository/cg3-backend'
        - PolicyName: CG3_S3_Write_Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: S3Access
                Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource:
                  - 'arn:aws:s3:::careguard-frontend-test-bucket'
                  - 'arn:aws:s3:::careguard-frontend-test-bucket/*'
        - PolicyName: CG3_CloudFront_Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudFrontAccess
                Effect: Allow
                Action: 'cloudfront:CreateInvalidation'
                Resource: !Join ["", ["arn:aws:cloudfront::", !Ref Account, ":distribution/", !Ref CloudFrontDistID] ]
                #Resource: 'arn:aws:cloudfront::300899438431:distribution/E1DFZCGNU1GLB8'
        - PolicyName: CG3_Lambda_Write_Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: LambdaAccess
                Effect: Allow
                Action: lambda:UpdateFunctionCode
                Resource:
                  - !Join ["", ["arn:aws:lambda:us-east-1:", !Ref Account, ":function:careguard-user-migration-test"] ]
                  #- 'arn:aws:lambda:us-east-1:300899438431:function:careguard-user-migration-test'
                  - !Join ["", ["arn:aws:lambda:us-east-1:", !Ref Account, ":function:careguard-pretoken-generator-test"] ]
                  #- 'arn:aws:lambda:us-east-1:300899438431:function:careguard-pretoken-generator-test'
      Tags:
        - Key: Created
          Value: !Ref CreationDate
        - Key: Creator
          Value: !Ref CreatedBy
        - Key: Application
          Value: !Ref Application
      UserName: !Ref Username

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "IAM User Information"
        Parameters:
          - Username
      - Label:
          default: "Tags"
        Parameters:
          - CreationDate
          - CreatedBy
          - Application
          - Owner

Outputs:
  IAMUserARN:
    Description: New IAM User ARN
    Value: !GetAtt IAMuser.Arn
    Export:
      Name: CG3IAMUserArn
  ManagedPolicyARN:
    Description: New IAM Managed Policy ARN
    Value: !Ref IAMpolicy