---
# Author: Brian Gaber
# BB Modernization Cloudformation Template
# Stack can be created from the console or from the AWS CLI.
# If stack is created from the console then resources will be created in the region shown in the upper right.
# If stack is created from the AWS CLI then the region flag must be used or the stack will be created in the AWS default region (us-east-1).
# Example of creating stack from the AWS CLI:
# aws --region us-east-1 cloudformation create-stack --stack-name amazon-mq-stack --template-body file://amz-mq.json --parameters ParameterKey=ActualParamName,ParameterValue=ActualParamValue
# This CloudFormation Template will create the following resources:
# - Amazon MQ Broker

Parameters:
  CreationDate:
    Description: Creation Date
    Type: String
    Default: "2023-02-09 10:30:00"
    AllowedPattern: "^\\d{4}(-\\d{2}){2} (\\d{2}:){2}\\d{2}$"
    ConstraintDescription: Date and time of creation
  CreatedBy:
    Description: Tool used to create resources
    Default: CloudFormation
    Type: String
  Application:
    Description: Application Name
    Default: BB Modernization
    Type: String
  Owner:
    Description: Application Owner
    Default: Mike Legato
    Type: String
  InstanceType:
    Type: String
    Default: mq.m5.xlarge
    AllowedValues:
      - mq.t2.micro
      - mq.t3.micro
      - mq.m4.large
      - mq.m5.large
      - mq.m5.xlarge
      - mq.m5.2xlarge
      - mq.m5.4xlarge
    Description: Enter mq.t2.micro, mq.t3.micro, mq.m4.large, mq.m5.large, mq.m5.xlarge, mq.m5.2xlarge or mq.m5.4xlarge. Default is mq.m5.xlarge.
  MqPrivSubnets:
    Description: Amazon MQ Private Subnets
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-123xyz, subnet-890abc"
  MqSecurityGroups:
    Description: Amazon MQ Security Groups
    Type: List<AWS::EC2::SecurityGroup::GroupName>
    Default: "sg-123xyz, sg-890abc"
  Username:
    Description: An ActiveMQ user is a person or an application that can access the queues and topics of an ActiveMQ broker.
    Type: String
    Default: fudde
  Password:
    Description: Password of the ActiveMQ user
    Type: String
    Default: Password123
    NoEcho: true
  AWSaccount:
    Description: The AWS Account for this deployment
    Type: String
    Default: 995437807815

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Amazon MQ"
        Parameters:
          - InstanceType
          - MqPrivSubnets
          - MqSecurityGroups
          - Username
          - Password
      - Label:
          default: "Tags"
        Parameters:
          - CreationDate
          - CreatedBy
          - Application
          - Owner
    ParameterLabels:
      InstanceType:
        default: "What is the desired instance type for this Amazon MQ Broker?"
      MqPrivSubnets:
        default: "What are the Subnets for this Amazon MQ Broker?"
      MqSecurityGroups:
        default: "What are the Security Groups for this Amazon MQ Broker?"
      AWSaccount:
        default: "What is the AWS Account for this deployment"

Resources:
  AmazonMqBroker:
    Type: AWS::AmazonMQ::Broker
    Properties: 
      AuthenticationStrategy: Simple
      AutoMinorVersionUpgrade: true
      BrokerName: BB Modernization Amazon MQ Broker
      DeploymentMode: ACTIVE_STANDBY_MULTI_AZ
      EngineType: ACTIVEMQ
      EngineVersion: 5.17.2
      HostInstanceType: !Ref InstanceType
      MaintenanceWindowStartTime: 
        DayOfWeek: Sunday
        TimeOfDay: 02:00:00
        TimeZone: EST
      PubliclyAccessible: false
      SecurityGroups: !Ref MqSecurityGroups
      #StorageType: String
      SubnetIds: !Ref MqPrivSubnets
      Tags:
        - Key: Created
          Value: !Ref CreationDate
        - Key: Creator
          Value: !Ref CreatedBy
        - Key: Application
          Value: !Ref Application
        - Key: Owner
          Value: !Ref Owner
      Users: 
        - ConsoleAccess: true
          Password: !Ref Password
          Username: !Ref Username

Outputs:
  AmazonMqBrokerID:
    Description: Amazon MQ Broker ID
    Value: !Ref AmazonMqBroker
  AmazonMqBrokerEndPt:
    Description: Amazon MQ Broker Endpoint
    Value: !GetAtt AmazonMqBroker.AmqpEndpoints
  AmazonMqBrokerArn:
    Description: Amazon MQ Broker Arn
    Value: !GetAtt AmazonMqBroker.Arn